var notices = 
[
  {
    "_id": "54d3aae74c08cd9ed0600a72",
    "nid": "1073",
    "socid": "3e115ca1-6386-438b-9313-f62f9ce4a8a8",
    "uid": "fc8d0419-a912-4a05-ba16-8af44ae9cd77",
    "isactive": true,
    "title": "Table Tennis Tournament",
    "contentshort": "Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing consectetur adipiscing consectetur adipiscing...",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mattis odio. In hac habitasse platea dictumst. Vestibulum volutpat pretium porta. Cras mattis metus non ipsum porttitor pulvinar. Proin tempus erat ac neque gravida suscipit. Morbi faucibus turpis a turpis hendrerit sodales sed vel nisl. Praesent vitae magna luctus, blandit quam eu, semper mi.",
    "byname": "Hester Tanner",
    "byposition": "Manager",
    "bydepartment": "Facilities Management Dept",
    "bysocietyname": "Elita Promenade",
    "valdifor": 10,
    "createdat": "2015-02-15T13:03:07.588Z",
    "expiry": "2015-02-25T13:03:07.588Z"
  },
  {
    "_id": "54d3aae7bf4248d3cec1d640",
    "nid": "1063",
    "socid": "3e115ca1-6386-438b-9313-f62f9ce4a8a8",
    "uid": "fc8d0419-a912-4a05-ba16-8af44ae9cd77",
    "isactive": true,
    "title": "Water Management",
    "contentshort": "Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing consectetur adipiscing consectetur adipiscing...",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mattis odio. In hac habitasse platea dictumst. Vestibulum volutpat pretium porta. Cras mattis metus non ipsum porttitor pulvinar. Proin tempus erat ac neque gravida suscipit. Morbi faucibus turpis a turpis hendrerit sodales sed vel nisl. Praesent vitae magna luctus, blandit quam eu, semper mi.",
    "byname": "Lois England",
    "bydepartment": "RWA",
    "byposition": "President",
    "societyname": "Elita Promenade",
    "valdifor": 30,
    "createdat": "2015-02-25T13:03:07.588Z",
    "expiry": "2015-03-25T13:03:07.588Z"
  },
  {
    "_id": "54d3aae78672eda2b93794c4",
    "nid": "1089",
    "socid": "3e115ca1-6386-438b-9313-f62f9ce4a8a8",
    "uid": "fc8d0419-a912-4a05-ba16-8af44ae9cd77",
    "isactive": true,
    "title": "Eid Fest",
    "contentshort": "Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing consectetur adipiscing consectetur adipiscing...",
    "contenturl": "http://www.localhost:8080/notice-content",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mattis odio. In hac habitasse platea dictumst. Vestibulum volutpat pretium porta. Cras mattis metus non ipsum porttitor pulvinar. Proin tempus erat ac neque gravida suscipit. Morbi faucibus turpis a turpis hendrerit sodales sed vel nisl. Praesent vitae magna luctus, blandit quam eu, semper mi.",
    "byname": "Elizabeth Flynn",
    "bydepartment": "Club",
    "byposition": "Vice President",
    "societyname": "Elita Promenade",
    "valdifor": 45,
    "createdat": "2015-01-20T13:03:07.588Z",
    "expiry": "2015-03-05T13:03:07.588Z"
  },
  {
    "_id": "54d3aae7113488afbdd7650a",
    "nid": "1065",
    "socid": "22a9030f-6e6a-4806-9c9a-fe98776c9bf6",
    "uid": "c15d6a91-3b32-4bf1-a86a-cf9046ec8ce1",
    "isactive": true,
    "title": "Diwali Celebrations",
    "contentshort": "Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing consectetur adipiscing consectetur adipiscing...",
    "contenturl": "http://www.localhost:8080/notice-content",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mattis odio. In hac habitasse platea dictumst. Vestibulum volutpat pretium porta. Cras mattis metus non ipsum porttitor pulvinar. Proin tempus erat ac neque gravida suscipit. Morbi faucibus turpis a turpis hendrerit sodales sed vel nisl. Praesent vitae magna luctus, blandit quam eu, semper mi.",
    "byname": "Miriam Sargent",
    "byposition": "Head Guard",
    "bydepartment": "Club",
    "societyname": "Brigade Millenium",
    "valdifor": 30,
    "createdat": "2015-02-28T13:03:07.588Z",
    "expiry": "2015-03-28T13:03:07.588Z"
  },
  {
    "_id": "54d3aae7dd1016ae8c461f1c",
    "nid": "1017",
    "socid": "22a9030f-6e6a-4806-9c9a-fe98776c9bf6",
    "uid": "c15d6a91-3b32-4bf1-a86a-cf9046ec8ce1",
    "isactive": true,
    "title": "Annual Function",
    "contentshort": "Lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing consectetur adipiscing consectetur adipiscing...",
    "contenturl": "http://www.localhost:8080/notice-content",
    "desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec mattis odio. In hac habitasse platea dictumst. Vestibulum volutpat pretium porta. Cras mattis metus non ipsum porttitor pulvinar. Proin tempus erat ac neque gravida suscipit. Morbi faucibus turpis a turpis hendrerit sodales sed vel nisl. Praesent vitae magna luctus, blandit quam eu, semper mi.",
    "byname": "Crane Keller",
    "byposition": "Manager",
    "bydepartment": "Club",
    "societyname": "Brigade Millenium",
    "valdifor": 120,
    "createdat": "2014-12-18T13:03:07.588Z",
    "expiry": "2015-04-18T13:03:07.588Z"
  }
]

module.exports.notices = notices;